[oss] Switch to C++20
Hopefully fixes this: https://github.com/simonmar/hsthrift/actions/runs/17289097408/job/49072047962

```
/github/home/.hsthrift/include/thrift/lib/cpp2/Thrift.h:34:21: error: static assertion failed: Thrift must be built with C++20 or later.
   34 |     FOLLY_CPLUSPLUS >= 202002L, "Thrift must be built with C++20
   or later.");
```

Safest thing is probably to move to `--std=c++20` everywhere.