Add libfmt v8 as a dependency
folly has recently moved to strictly depend on libfmt 8. libfmt 7 now
produces compilation errors.

> error: passing ‘const fmt::v7::formatter<folly::Range<const char*> >’ as ‘this’ argument discards qualifiers [-fpermissive]

We can avoid this by adding (another) source dependency. libfmt is small so overhead is tiny.
Fix up the CI to drop libfmt as well