Fix missing fixturesPath variable
Summary:
Fixes the error:

```
test/TestFixtures.hs:72:37: error:
    Variable not in scope: fixturesPath :: [Char]
   |
72 |     mname = tail $ snd $ breakOnEnd fixturesPath tmPath
   |
```

Reviewed By: josefs

Differential Revision: D41385769

fbshipit-source-id: 78cb9849b28181c91305b0c7200ad736f7ac2fc3