Fix qualifier bug
Summary:
When compiling my thrift code into haskell, I got a compile error on the generated Service.hs saying a symbol was not found, and perhaps I forgot to prefix is with `Types.`:
```
buck-out/v2/gen/fbcode/a81beb8075982250/glean/glass/if/__glass-hs2-glass.thrift__/out/gen-hs2/Glean/Glass/GlassService/Service.hs:864:71: error:
    • Variable not in scope: unSymbolId :: Types.SymbolId -> Text.Text
    • Perhaps you meant one of these:
        ‘Types.unSymbolId’ (imported from Glean.Glass.Types),
        data constructor ‘Types.SymbolId’ (imported from Glean.Glass.Types)
    |
864 |                                              (Thrift.genText _proxy . unSymbolId)
    |                                                                       ^^^^^^^^^^
```

Upon inspection of GenService.hs, which deals with generating Service.hs, one can see a few calls to `qualifyType "Types"` and `qualifyField "Types"`. With the same logic, we should also qualify the function types of the methods we generate, which is what this diff does.

There's probably a more general fix to that:
* refactor all the qualifyXXX functions into a type class
* don't cherry pick what we qualify in GenService.hs, qualify everything

Reviewed By: helfper

Differential Revision: D72380181

fbshipit-source-id: a8a848babccae25802f8f30da3a2a8f2c1318b20