cpp-channel: Do not link libfolly dynamically
libfolly is included statically in fbthrift. Linking libfolly both statically
will cause the linker check of gflags to fail with the message:

  ERROR: something wrong with flag 'folly_memory_idler_purge_arenas' in
  file 'folly/detail/MemoryIdler.cpp'.
    One possibility: file 'folly/detail/MemoryIdler.cpp' is being
    linked both statically and dynamically into this executable.

coming from:
https://chromium.googlesource.com/external/gflags/src/+/b85dc3e1691f7106fd4fd54deb225088be14bc16/gflags.cc#726

Removing libfolly from dynamic linking will result in thrift-cpp-channel
to correctly compile.